version: 2
registries:
  # dspnightly:
  #   type: nuget-feed
  #   url: https://nuget.emzi0767.com/api/v3/index.json
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    directory: "/"
    registries: "*"
    schedule:
      interval: daily
