version: '2.3'
services:
  bot:
    build: .
    env_file:
      - .env
    restart: on-failure
    volumes:
      - type: bind
        source: ./Ranker/config.json
        target: /app/config.json
    ports:
      - 127.0.0.1:8080:80
