name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Initialize submodules
          run: git submodule update --init
        - name: Set secrets
          run: flyctl secrets set RANKER_TOKEN="${{ secrets.BOT_TOKEN }}" && flyctl secrets set RANKER_CLIENT_SECRET="${{ secrets.BOT_SECRET }}" && flyctl secrets set PREFIX='${{ secrets.PREFIX }}' && flyctl secrets set DOMAIN="${{ secrets.DOMAIN }}" && flyctl secrets set CLIENT_ID="${{ secrets.CLIENT_ID }}"
        - name: Deploy app
          run: flyctl deploy --remote-only
